services:
  - type: web
    name: physicstuff-streamlit
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
